name: Pull Request Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Aktualisiert auf die für Node24 optimierte Version 4 (oder höher)
    - name: Code auschecken
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Aktualisiert auf die aktuelle Version v4.3.0+ / v5 mit Node24-Support
    - name: Java JDK 21 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven settings.xml temporär für CI generieren
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>s0564632</username><password>${{ secrets.OSSD_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

    - name: Automated Maven Tests ausführen
      run: mvn clean test
