name: Pull Request Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Erlaubt der Pipeline ausdrücklich das Lesen von externen GitHub Packages
    permissions:
      contents: read
      packages: read

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Java JDK 17 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven settings.xml temporär für CI generieren
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>s0564632</username><password>\${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

    - name: Automated Maven Tests ausführen
      run: mvn clean test
