name: Pull Request Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java JDK 21 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github-prose-builder
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.OSSD_TOKEN }}

      - name: Automated Maven Tests ausführen
        run: mvn clean test